class InsertPlayers < ActiveRecord::Migration

  def change
    FootballPlayer.create(first_name: "David", last_name: "Akers", position: "K", player_id: 5352)
    FootballPlayer.create(first_name: "Sebastian", last_name: "Janikowski", position: "K", player_id: 3253)
    FootballPlayer.create(first_name: "Rob", last_name: "Bironas", position: "K", player_id: 2616)
    FootballPlayer.create(first_name: "Dan", last_name: "Bailey", position: "K", player_id: 13109)
    FootballPlayer.create(first_name: "Connor", last_name: "Barth", position: "K", player_id: 10092)
    FootballPlayer.create(first_name: "Robbie", last_name: "Gould", position: "K", player_id: 1410)
    FootballPlayer.create(first_name: "Josh", last_name: "Scobee", position: "K", player_id: 6902)
    FootballPlayer.create(first_name: "Mike", last_name: "Nugent", position: "K", player_id: 11735)
    FootballPlayer.create(first_name: "Dan", last_name: "Carpenter", position: "K", player_id: 1269)
    FootballPlayer.create(first_name: "Neil", last_name: "Rackers", position: "K", player_id: 11796)
    FootballPlayer.create(first_name: "Matt", last_name: "Bryant", position: "K", player_id: 3388)
    FootballPlayer.create(first_name: "Phil", last_name: "Dawson", position: "K", player_id: 5714)
    FootballPlayer.create(first_name: "Stephen", last_name: "Gostkowski", position: "K", player_id: 2982)
    FootballPlayer.create(first_name: "Jason", last_name: "Hanson", position: "K", player_id: 6131)
    FootballPlayer.create(first_name: "Mason", last_name: "Crosby", position: "K", player_id: 1694)
    FootballPlayer.create(first_name: "Steven", last_name: "Hauschka", position: "K", player_id: 12594)
    FootballPlayer.create(first_name: "Billy", last_name: "Cundiff", position: "K", player_id: 10145)
    FootballPlayer.create(first_name: "Adam", last_name: "Vinatieri", position: "K", player_id: 3258)
    FootballPlayer.create(first_name: "Graham", last_name: "Gano", position: "K", player_id: 10333)
    FootballPlayer.create(first_name: "Ryan", last_name: "Succop", position: "K", player_id: 8750)
    FootballPlayer.create(first_name: "Alex", last_name: "Henery", position: "K", player_id: 12702)
    FootballPlayer.create(first_name: "Nick", last_name: "Folk", position: "K", player_id: 11694)
    FootballPlayer.create(first_name: "Olindo", last_name: "Mare", position: "K", player_id: 5106)
    FootballPlayer.create(first_name: "Matt", last_name: "Prater", position: "K", player_id: 549)
    FootballPlayer.create(first_name: "Josh", last_name: "Brown", position: "K", player_id: 2695)
    FootballPlayer.create(first_name: "Shaun", last_name: "Suisham", position: "K", player_id: 12508)
    FootballPlayer.create(first_name: "Jay", last_name: "Feely", position: "K", player_id: 12088)
    FootballPlayer.create(first_name: "Lawrence", last_name: "Tynes", position: "K", player_id: 4137)
    FootballPlayer.create(first_name: "Rian", last_name: "Lindell", position: "K", player_id: 6410)
    FootballPlayer.create(first_name: "John", last_name: "Potter", position: "K", player_id: 13767)
    FootballPlayer.create(first_name: "Greg", last_name: "Zuerlein", position: "K", player_id: 14697)
    FootballPlayer.create(first_name: "Blair", last_name: "Walsh", position: "K", player_id: 14463)
    FootballPlayer.create(first_name: "Garrett", last_name: "Hartley", position: "K", player_id: 418)
    FootballPlayer.create(first_name: "Nate", last_name: "Kaeding", position: "K", player_id: 1461)
    FootballPlayer.create(first_name: "Randy", last_name: "Bullock", position: "K", player_id: 13961)
    FootballPlayer.create(first_name: "Drew", last_name: "Brees", position: "QB", player_id: 7242)
    FootballPlayer.create(first_name: "Aaron", last_name: "Rodgers", position: "QB", player_id: 2593)
    FootballPlayer.create(first_name: "Tom", last_name: "Brady", position: "QB", player_id: 4314)
    FootballPlayer.create(first_name: "Cam", last_name: "Newton", position: "QB", player_id: 13320)
    FootballPlayer.create(first_name: "Matthew", last_name: "Stafford", position: "QB", player_id: 9038)
    FootballPlayer.create(first_name: "Eli", last_name: "Manning", position: "QB", player_id: 4932)
    FootballPlayer.create(first_name: "Tony", last_name: "Romo", position: "QB", player_id: 3867)
    FootballPlayer.create(first_name: "Matt", last_name: "Ryan", position: "QB", player_id: 732)
    FootballPlayer.create(first_name: "Philip", last_name: "Rivers", position: "QB", player_id: 8244)
    FootballPlayer.create(first_name: "Michael", last_name: "Vick", position: "QB", player_id: 9447)
    FootballPlayer.create(first_name: "Ben", last_name: "Roethlisberger", position: "QB", player_id: 3807)
    FootballPlayer.create(first_name: "Alex", last_name: "Smith", position: "QB", player_id: 6739)
    FootballPlayer.create(first_name: "Ryan", last_name: "Fitzpatrick", position: "QB", player_id: 8283)
    FootballPlayer.create(first_name: "Matt", last_name: "Hasselbeck", position: "QB", player_id: 1034)
    FootballPlayer.create(first_name: "Andy", last_name: "Dalton", position: "QB", player_id: 12841)
    FootballPlayer.create(first_name: "Josh", last_name: "Freeman", position: "QB", player_id: 9226)
    FootballPlayer.create(first_name: "Joe", last_name: "Flacco", position: "QB", player_id: 611)
    FootballPlayer.create(first_name: "Mark", last_name: "Sanchez", position: "QB", player_id: 8415)
    FootballPlayer.create(first_name: "Matt", last_name: "Schaub", position: "QB", player_id: 4633)
    FootballPlayer.create(first_name: "Carson", last_name: "Palmer", position: "QB", player_id: 2428)
    FootballPlayer.create(first_name: "Tim", last_name: "Tebow", position: "QB", player_id: 11196)
    FootballPlayer.create(first_name: "Tarvaris", last_name: "Jackson", position: "QB", player_id: 4097)
    FootballPlayer.create(first_name: "Matt", last_name: "Moore", position: "QB", player_id: 5834)
    FootballPlayer.create(first_name: "Jay", last_name: "Cutler", position: "QB", player_id: 8972)
    FootballPlayer.create(first_name: "Colt", last_name: "McCoy", position: "QB", player_id: 11047)
    FootballPlayer.create(first_name: "Rex", last_name: "Grossman", position: "QB", player_id: 11952)
    FootballPlayer.create(first_name: "Kevin", last_name: "Kolb", position: "QB", player_id: 7034)
    FootballPlayer.create(first_name: "Christian", last_name: "Ponder", position: "QB", player_id: 13270)
    FootballPlayer.create(first_name: "John", last_name: "Skelton", position: "QB", player_id: 11567)
    FootballPlayer.create(first_name: "Matt", last_name: "Cassel", position: "QB", player_id: 8723)
    FootballPlayer.create(first_name: "Kyle", last_name: "Orton", position: "QB", player_id: 8703)
    FootballPlayer.create(first_name: "Jason", last_name: "Campbell", position: "QB", player_id: 11859)
    FootballPlayer.create(first_name: "Chad", last_name: "Henne", position: "QB", player_id: 2405)
    FootballPlayer.create(first_name: "Sam", last_name: "Bradford", position: "QB", player_id: 11527)
    FootballPlayer.create(first_name: "Curtis", last_name: "Painter", position: "QB", player_id: 8621)
    FootballPlayer.create(first_name: "Blaine", last_name: "Gabbert", position: "QB", player_id: 12982)
    FootballPlayer.create(first_name: "Dan", last_name: "Orlovsky", position: "QB", player_id: 8590)
    FootballPlayer.create(first_name: "Jake", last_name: "Locker", position: "QB", player_id: 12925)
    FootballPlayer.create(first_name: "John", last_name: "Beck", position: "QB", player_id: 11942)
    FootballPlayer.create(first_name: "T.J.", last_name: "Yates", position: "QB", player_id: 12956)
    FootballPlayer.create(first_name: "Joe", last_name: "Webb", position: "QB", player_id: 11422)
    FootballPlayer.create(first_name: "Matt", last_name: "Flynn", position: "QB", player_id: 3895)
    FootballPlayer.create(first_name: "Vince", last_name: "Young", position: "QB", player_id: 4124)
    FootballPlayer.create(first_name: "Kellen", last_name: "Clemens", position: "QB", player_id: 5054)
    FootballPlayer.create(first_name: "Seneca", last_name: "Wallace", position: "QB", player_id: 11755)
    FootballPlayer.create(first_name: "Josh", last_name: "McCown", position: "QB", player_id: 5282)
    FootballPlayer.create(first_name: "Caleb", last_name: "Hanie", position: "QB", player_id: 7755)
    FootballPlayer.create(first_name: "Stephen", last_name: "McGee", position: "QB", player_id: 8844)
    FootballPlayer.create(first_name: "Josh", last_name: "Johnson", position: "QB", player_id: 6489)
    FootballPlayer.create(first_name: "Charlie", last_name: "Batch", position: "QB", player_id: 5486)
    FootballPlayer.create(first_name: "Charlie", last_name: "Whitehurst", position: "QB", player_id: 12137)
    FootballPlayer.create(first_name: "Chris", last_name: "Redman", position: "QB", player_id: 8064)
    FootballPlayer.create(first_name: "Matt", last_name: "Leinart", position: "QB", player_id: 12201)
    FootballPlayer.create(first_name: "Bruce", last_name: "Gradkowski", position: "QB", player_id: 8769)
    FootballPlayer.create(first_name: "Shaun", last_name: "Hill", position: "QB", player_id: 11992)
    FootballPlayer.create(first_name: "Tyrod", last_name: "Taylor", position: "QB", player_id: 12831)
    FootballPlayer.create(first_name: "Colin", last_name: "Kaepernick", position: "QB", player_id: 13443)
    FootballPlayer.create(first_name: "Chase", last_name: "Daniel", position: "QB", player_id: 9902)
    FootballPlayer.create(first_name: "Brian", last_name: "Hoyer", position: "QB", player_id: 8358)
    FootballPlayer.create(first_name: "Jordan", last_name: "Palmer", position: "QB", player_id: 1482)
    FootballPlayer.create(first_name: "Brandon", last_name: "Weeden", position: "QB", player_id: 13910)
    FootballPlayer.create(first_name: "Brady", last_name: "Quinn", position: "QB", player_id: 11838)
    FootballPlayer.create(first_name: "Brock", last_name: "Osweiler", position: "QB", player_id: 14053)
    FootballPlayer.create(first_name: "Drew", last_name: "Stanton", position: "QB", player_id: 4737)
    FootballPlayer.create(first_name: "Rusty", last_name: "Smith", position: "QB", player_id: 12301)
    FootballPlayer.create(first_name: "Peyton", last_name: "Manning", position: "QB", player_id: 7328)
    FootballPlayer.create(first_name: "Andrew", last_name: "Luck", position: "QB", player_id: 14008)
    FootballPlayer.create(first_name: "Chandler", last_name: "Harnish", position: "QB", player_id: 14002)
    FootballPlayer.create(first_name: "Ricky", last_name: "Stanzi", position: "QB", player_id: 13048)
    FootballPlayer.create(first_name: "Terrell", last_name: "Pryor", position: "QB", player_id: 13693)
    FootballPlayer.create(first_name: "Sage", last_name: "Rosenfels", position: "QB", player_id: 12244)
    FootballPlayer.create(first_name: "Ryan", last_name: "Tannehill", position: "QB", player_id: 13799)
    FootballPlayer.create(first_name: "Ryan", last_name: "Mallett", position: "QB", player_id: 12771)
    FootballPlayer.create(first_name: "David", last_name: "Carr", position: "QB", player_id: 12104)
    FootballPlayer.create(first_name: "Nick", last_name: "Foles", position: "QB", player_id: 13723)
    FootballPlayer.create(first_name: "Byron", last_name: "Leftwich", position: "QB", player_id: 1036)
    FootballPlayer.create(first_name: "Russell", last_name: "Wilson", position: "QB", player_id: 14536)
    FootballPlayer.create(first_name: "Robert", last_name: "Griffin", position: "QB", player_id: 14257)
    FootballPlayer.create(first_name: "Jimmy", last_name: "Clausen", position: "QB", player_id: 11447)
    FootballPlayer.create(first_name: "David", last_name: "Garrard", position: "QB", player_id: 1185)
    FootballPlayer.create(first_name: "Kellen", last_name: "Moore", position: "QB", player_id: 14219)
    FootballPlayer.create(first_name: "Graham", last_name: "Harrell", position: "QB", player_id: 12635)
    FootballPlayer.create(first_name: "Mike", last_name: "Kafka", position: "QB", player_id: 11323)
    FootballPlayer.create(first_name: "Derek", last_name: "Anderson", position: "QB", player_id: 12083)
    FootballPlayer.create(first_name: "Tom", last_name: "Brandstater", position: "QB", player_id: 8673)
    FootballPlayer.create(first_name: "Luke", last_name: "McCown", position: "QB", player_id: 6276)
    FootballPlayer.create(first_name: "Ray", last_name: "Rice", position: "RB", player_id: 547)
    FootballPlayer.create(first_name: "LeSean", last_name: "McCoy", position: "RB", player_id: 11932)
    FootballPlayer.create(first_name: "Maurice", last_name: "Jones-Drew", position: "RB", player_id: 7308)
    FootballPlayer.create(first_name: "Arian", last_name: "Foster", position: "RB", player_id: 11792)
    FootballPlayer.create(first_name: "Darren", last_name: "Sproles", position: "RB", player_id: 6198)
    FootballPlayer.create(first_name: "Ryan", last_name: "Mathews", position: "RB", player_id: 11256)
    FootballPlayer.create(first_name: "Michael", last_name: "Turner", position: "RB", player_id: 8016)
    FootballPlayer.create(first_name: "Marshawn", last_name: "Lynch", position: "RB", player_id: 12386)
    FootballPlayer.create(first_name: "Fred", last_name: "Jackson", position: "RB", player_id: 5701)
    FootballPlayer.create(first_name: "Reggie", last_name: "Bush", position: "RB", player_id: 4640)
    FootballPlayer.create(first_name: "Matt", last_name: "Forte", position: "RB", player_id: 2699)
    FootballPlayer.create(first_name: "Steven", last_name: "Jackson", position: "RB", player_id: 1652)
    FootballPlayer.create(first_name: "Adrian", last_name: "Peterson(Min)", position: "RB", player_id: 4807)
    FootballPlayer.create(first_name: "Michael", last_name: "Bush", position: "RB", player_id: 371)
    FootballPlayer.create(first_name: "Chris", last_name: "Johnson(TEN)", position: "RB", player_id: 6828)
    FootballPlayer.create(first_name: "Jonathan", last_name: "Stewart", position: "RB", player_id: 5451)
    FootballPlayer.create(first_name: "Frank", last_name: "Gore", position: "RB", player_id: 5820)
    FootballPlayer.create(first_name: "Shonn", last_name: "Greene", position: "RB", player_id: 8399)
    FootballPlayer.create(first_name: "DeAngelo", last_name: "Williams", position: "RB", player_id: 7580)
    FootballPlayer.create(first_name: "Beanie", last_name: "Wells", position: "RB", player_id: 9323)
    FootballPlayer.create(first_name: "Willis", last_name: "McGahee", position: "RB", player_id: 7451)
    FootballPlayer.create(first_name: "Mike", last_name: "Tolbert", position: "RB", player_id: 4738)
    FootballPlayer.create(first_name: "Pierre", last_name: "Thomas", position: "RB", player_id: 957)
    FootballPlayer.create(first_name: "DeMarco", last_name: "Murray", position: "RB", player_id: 13124)
    FootballPlayer.create(first_name: "Ahmad", last_name: "Bradshaw", position: "RB", player_id: 2220)
    FootballPlayer.create(first_name: "Ben", last_name: "Tate", position: "RB", player_id: 13557)
    FootballPlayer.create(first_name: "C.J.", last_name: "Spiller", position: "RB", player_id: 10949)
    FootballPlayer.create(first_name: "BenJarvus", last_name: "Green-Ellis", position: "RB", player_id: 462)
    FootballPlayer.create(first_name: "Cedric", last_name: "Benson", position: "RB", player_id: 1351)
    FootballPlayer.create(first_name: "Roy", last_name: "Helu", position: "RB", player_id: 13163)
    FootballPlayer.create(first_name: "Darren", last_name: "McFadden", position: "RB", player_id: 8066)
    FootballPlayer.create(first_name: "Donald", last_name: "Brown", position: "RB", player_id: 8604)
    FootballPlayer.create(first_name: "LeGarrette", last_name: "Blount", position: "RB", player_id: 12296)
    FootballPlayer.create(first_name: "Brandon", last_name: "Jacobs", position: "RB", player_id: 2254)
    FootballPlayer.create(first_name: "Toby", last_name: "Gerhart", position: "RB", player_id: 11413)
    FootballPlayer.create(first_name: "Ryan", last_name: "Grant", position: "RB", player_id: 3680)
    FootballPlayer.create(first_name: "Jahvid", last_name: "Best", position: "RB", player_id: 11373)
    FootballPlayer.create(first_name: "James", last_name: "Starks", position: "RB", player_id: 12506)
    FootballPlayer.create(first_name: "Felix", last_name: "Jones", position: "RB", player_id: 7290)
    FootballPlayer.create(first_name: "Kevin", last_name: "Smith", position: "RB", player_id: 194)
    FootballPlayer.create(first_name: "Kendall", last_name: "Hunter", position: "RB", player_id: 13440)
    FootballPlayer.create(first_name: "Peyton", last_name: "Hillis", position: "RB", player_id: 11747)
    FootballPlayer.create(first_name: "Mark", last_name: "Ingram", position: "RB", player_id: 13337)
    FootballPlayer.create(first_name: "Isaac", last_name: "Redman", position: "RB", player_id: 8519)
    FootballPlayer.create(first_name: "Danny", last_name: "Woodhead", position: "RB", player_id: 12317)
    FootballPlayer.create(first_name: "Stevan", last_name: "Ridley", position: "RB", player_id: 12774)
    FootballPlayer.create(first_name: "Daniel", last_name: "Thomas", position: "RB", player_id: 12762)
    FootballPlayer.create(first_name: "Kahlil", last_name: "Bell", position: "RB", player_id: 10161)
    FootballPlayer.create(first_name: "Kregg", last_name: "Lumpkin", position: "RB", player_id: 12297)
    FootballPlayer.create(first_name: "Evan", last_name: "Royster", position: "RB", player_id: 13172)
    FootballPlayer.create(first_name: "LaRod", last_name: "Stephens-Howling", position: "RB", player_id: 9319)
    FootballPlayer.create(first_name: "Bernard", last_name: "Scott", position: "RB", player_id: 8455)
    FootballPlayer.create(first_name: "Tim", last_name: "Hightower", position: "RB", player_id: 2262)
    FootballPlayer.create(first_name: "Jacquizz", last_name: "Rodgers", position: "RB", player_id: 13299)
    FootballPlayer.create(first_name: "Jason", last_name: "Snelling", position: "RB", player_id: 5412)
    FootballPlayer.create(first_name: "D.J.", last_name: "Ware", position: "RB", player_id: 3600)
    FootballPlayer.create(first_name: "Javon", last_name: "Ringer", position: "RB", player_id: 9556)
    FootballPlayer.create(first_name: "Leon", last_name: "Washington", position: "RB", player_id: 12136)
    FootballPlayer.create(first_name: "Justin", last_name: "Forsett", position: "RB", player_id: 9369)
    FootballPlayer.create(first_name: "Montario", last_name: "Hardesty", position: "RB", player_id: 13530)
    FootballPlayer.create(first_name: "Knowshon", last_name: "Moreno", position: "RB", player_id: 8699)
    FootballPlayer.create(first_name: "Delone", last_name: "Carter", position: "RB", player_id: 12959)
    FootballPlayer.create(first_name: "Joe", last_name: "McKnight", position: "RB", player_id: 10999)
    FootballPlayer.create(first_name: "Tashard", last_name: "Choice", position: "RB", player_id: 1891)
    FootballPlayer.create(first_name: "Curtis", last_name: "Brinkley", position: "RB", player_id: 11876)
    FootballPlayer.create(first_name: "Jonathan", last_name: "Dwyer", position: "RB", player_id: 12262)
    FootballPlayer.create(first_name: "Brandon", last_name: "Saine", position: "RB", player_id: 13241)
    FootballPlayer.create(first_name: "Dion", last_name: "Lewis", position: "RB", player_id: 12708)
    FootballPlayer.create(first_name: "Phillip", last_name: "Tanner", position: "RB", player_id: 13130)
    FootballPlayer.create(first_name: "Steve", last_name: "Slaton", position: "RB", player_id: 438)
    FootballPlayer.create(first_name: "Jamaal", last_name: "Charles", position: "RB", player_id: 7969)
    FootballPlayer.create(first_name: "Taiwan", last_name: "Jones", position: "RB", player_id: 13063)
    FootballPlayer.create(first_name: "Shane", last_name: "Vereen", position: "RB", player_id: 12780)
    FootballPlayer.create(first_name: "Ronnie", last_name: "Brown", position: "RB", player_id: 6458)
    FootballPlayer.create(first_name: "Jamie", last_name: "Harper", position: "RB", player_id: 12918)
    FootballPlayer.create(first_name: "Alex", last_name: "Green", position: "RB", player_id: 13232)
    FootballPlayer.create(first_name: "Mike", last_name: "Goodson", position: "RB", player_id: 9154)
    FootballPlayer.create(first_name: "Anthony", last_name: "Allen", position: "RB", player_id: 12807)
    FootballPlayer.create(first_name: "Brandon", last_name: "Jackson", position: "RB", player_id: 3898)
    FootballPlayer.create(first_name: "Trent", last_name: "Richardson", position: "RB", player_id: 13902)
    FootballPlayer.create(first_name: "Ronnie", last_name: "Hillman", position: "RB", player_id: 14046)
    FootballPlayer.create(first_name: "Mikel", last_name: "Leshoure", position: "RB", player_id: 13218)
    FootballPlayer.create(first_name: "Isaiah", last_name: "Pead", position: "RB", player_id: 14421)
    FootballPlayer.create(first_name: "Lamar", last_name: "Miller", position: "RB", player_id: 13791)
    FootballPlayer.create(first_name: "David", last_name: "Wilson", position: "RB", player_id: 14246)
    FootballPlayer.create(first_name: "Ryan", last_name: "Williams", position: "RB", player_id: 13425)
    FootballPlayer.create(first_name: "LaMichael", last_name: "James", position: "RB", player_id: 14501)
    FootballPlayer.create(first_name: "Doug", last_name: "Martin", position: "RB", player_id: 14385)
    FootballPlayer.create(first_name: "Rashad", last_name: "Jennings", position: "RB", player_id: 8649)
    FootballPlayer.create(first_name: "Bernard", last_name: "Pierce", position: "RB", player_id: 14687)
    FootballPlayer.create(first_name: "Rob", last_name: "Gronkowski", position: "TE", player_id: 10974)
    FootballPlayer.create(first_name: "Jimmy", last_name: "Graham", position: "TE", player_id: 11488)
    FootballPlayer.create(first_name: "Aaron", last_name: "Hernandez", position: "TE", player_id: 10975)
    FootballPlayer.create(first_name: "Jason", last_name: "Witten", position: "TE", player_id: 722)
    FootballPlayer.create(first_name: "Tony", last_name: "Gonzalez", position: "TE", player_id: 9108)
    FootballPlayer.create(first_name: "Brandon", last_name: "Pettigrew", position: "TE", player_id: 9588)
    FootballPlayer.create(first_name: "Antonio", last_name: "Gates", position: "TE", player_id: 7884)
    FootballPlayer.create(first_name: "Brent", last_name: "Celek", position: "TE", player_id: 5511)
    FootballPlayer.create(first_name: "Jermichael", last_name: "Finley", position: "TE", player_id: 3671)
    FootballPlayer.create(first_name: "Dustin", last_name: "Keller", position: "TE", player_id: 7692)
    FootballPlayer.create(first_name: "Vernon", last_name: "Davis", position: "TE", player_id: 5084)
    FootballPlayer.create(first_name: "Kellen", last_name: "Winslow", position: "TE", player_id: 9249)
    FootballPlayer.create(first_name: "Fred", last_name: "Davis", position: "TE", player_id: 2640)
    FootballPlayer.create(first_name: "Owen", last_name: "Daniels", position: "TE", player_id: 1810)
    FootballPlayer.create(first_name: "Jared", last_name: "Cook", position: "TE", player_id: 8534)
    FootballPlayer.create(first_name: "Jermaine", last_name: "Gresham", position: "TE", player_id: 11026)
    FootballPlayer.create(first_name: "Ed", last_name: "Dickson", position: "TE", player_id: 12153)
    FootballPlayer.create(first_name: "Heath", last_name: "Miller", position: "TE", player_id: 7635)
    FootballPlayer.create(first_name: "Greg", last_name: "Olsen", position: "TE", player_id: 1658)
    FootballPlayer.create(first_name: "Anthony", last_name: "Fasano", position: "TE", player_id: 1545)
    FootballPlayer.create(first_name: "Jeremy", last_name: "Shockey", position: "TE", player_id: 7980)
    FootballPlayer.create(first_name: "Scott", last_name: "Chandler", position: "TE", player_id: 12548)
    FootballPlayer.create(first_name: "Dennis", last_name: "Pitta", position: "TE", player_id: 11017)
    FootballPlayer.create(first_name: "Marcedes", last_name: "Lewis", position: "TE", player_id: 3061)
    FootballPlayer.create(first_name: "Benjamin", last_name: "Watson", position: "TE", player_id: 11756)
    FootballPlayer.create(first_name: "Joel", last_name: "Dreessen", position: "TE", player_id: 1577)
    FootballPlayer.create(first_name: "Tony", last_name: "Scheffler", position: "TE", player_id: 11998)
    FootballPlayer.create(first_name: "Evan", last_name: "Moore", position: "TE", player_id: 10290)
    FootballPlayer.create(first_name: "Kevin", last_name: "Boss", position: "TE", player_id: 543)
    FootballPlayer.create(first_name: "Dallas", last_name: "Clark", position: "TE", player_id: 244)
    FootballPlayer.create(first_name: "Jeff", last_name: "King", position: "TE", player_id: 2350)
    FootballPlayer.create(first_name: "Kyle", last_name: "Rudolph", position: "TE", player_id: 13275)
    FootballPlayer.create(first_name: "Lance", last_name: "Kendricks", position: "TE", player_id: 13386)
    FootballPlayer.create(first_name: "Todd", last_name: "Heap", position: "TE", player_id: 7140)
    FootballPlayer.create(first_name: "Kellen", last_name: "Davis", position: "TE", player_id: 8142)
    FootballPlayer.create(first_name: "Randy", last_name: "McMichael", position: "TE", player_id: 11882)
    FootballPlayer.create(first_name: "Leonard", last_name: "Pope", position: "TE", player_id: 9935)
    FootballPlayer.create(first_name: "Delanie", last_name: "Walker", position: "TE", player_id: 7175)
    FootballPlayer.create(first_name: "Zach", last_name: "Miller(Sea)", position: "TE", player_id: 4484)
    FootballPlayer.create(first_name: "Jacob", last_name: "Tamme", position: "TE", player_id: 852)
    FootballPlayer.create(first_name: "Clay", last_name: "Harbor", position: "TE", player_id: 11317)
    FootballPlayer.create(first_name: "Craig", last_name: "Stevens", position: "TE", player_id: 3)
    FootballPlayer.create(first_name: "Brandon", last_name: "Myers", position: "TE", player_id: 8778)
    FootballPlayer.create(first_name: "Martellus", last_name: "Bennett", position: "TE", player_id: 1181)
    FootballPlayer.create(first_name: "John", last_name: "Phillips", position: "TE", player_id: 8848)
    FootballPlayer.create(first_name: "Bear", last_name: "Pascoe", position: "TE", player_id: 10291)
    FootballPlayer.create(first_name: "Luke", last_name: "Stocker", position: "TE", player_id: 13370)
    FootballPlayer.create(first_name: "Michael", last_name: "Palmer", position: "TE", player_id: 11435)
    FootballPlayer.create(first_name: "Matt", last_name: "Spaeth", position: "TE", player_id: 6293)
    FootballPlayer.create(first_name: "Michael", last_name: "Hoomanawanui", position: "TE", player_id: 11535)
    FootballPlayer.create(first_name: "Chris", last_name: "Cooley", position: "TE", player_id: 6147)
    FootballPlayer.create(first_name: "Zach", last_name: "Miller(Jac)", position: "TE", player_id: 12415)
    FootballPlayer.create(first_name: "Andrew", last_name: "Quarless", position: "TE", player_id: 11400)
    FootballPlayer.create(first_name: "Jeff", last_name: "Cumberland", position: "TE", player_id: 10992)
    FootballPlayer.create(first_name: "David", last_name: "Thomas", position: "TE", player_id: 9764)
    FootballPlayer.create(first_name: "Lee", last_name: "Smith", position: "TE", player_id: 12777)
    FootballPlayer.create(first_name: "Garrett", last_name: "Graham", position: "TE", player_id: 11101)
    FootballPlayer.create(first_name: "David", last_name: "Ausberry", position: "TE", player_id: 13050)
    FootballPlayer.create(first_name: "Coby", last_name: "Fleener", position: "TE", player_id: 13997)
    FootballPlayer.create(first_name: "Dwayne", last_name: "Allen", position: "TE", player_id: 13987)
    FootballPlayer.create(first_name: "Tony", last_name: "Moeaki", position: "TE", player_id: 11221)
    FootballPlayer.create(first_name: "Michael", last_name: "Egnew", position: "TE", player_id: 14641)
    FootballPlayer.create(first_name: "John", last_name: "Carlson", position: "TE", player_id: 3878)
    FootballPlayer.create(first_name: "Calvin", last_name: "Johnson", position: "WR",player_id: 6029)
    FootballPlayer.create(first_name: "Wes", last_name: "Welker", position: "WR",player_id: 4631)
    FootballPlayer.create(first_name: "Victor", last_name: "Cruz", position: "WR",player_id: 12246)
    FootballPlayer.create(first_name: "Larry", last_name: "Fitzgerald", position: "WR",player_id: 5571)
    FootballPlayer.create(first_name: "Roddy", last_name: "White", position: "WR",player_id: 204)
    FootballPlayer.create(first_name: "Jordy", last_name: "Nelson", position: "WR",player_id: 4556)
    FootballPlayer.create(first_name: "Percy", last_name: "Harvin", position: "WR",player_id: 9079)
    FootballPlayer.create(first_name: "Steve", last_name: "Smith(Car)", position: "WR",player_id: 4358)
    FootballPlayer.create(first_name: "Mike", last_name: "Wallace", position: "WR",player_id: 8529)
    FootballPlayer.create(first_name: "Brandon", last_name: "Marshall(Chi)", position: "WR",player_id: 11667)
    FootballPlayer.create(first_name: "Hakeem", last_name: "Nicks", position: "WR",player_id: 9739)
    FootballPlayer.create(first_name: "Vincent", last_name: "Jackson", position: "WR",player_id: 3519)
    FootballPlayer.create(first_name: "Dwayne", last_name: "Bowe", position: "WR",player_id: 7203)
    FootballPlayer.create(first_name: "Marques", last_name: "Colston", position: "WR",player_id: 5094)
    FootballPlayer.create(first_name: "A.J.", last_name: "Green", position: "WR",player_id: 12845)
    FootballPlayer.create(first_name: "Nate", last_name: "Washington", position: "WR",player_id: 8564)
    FootballPlayer.create(first_name: "Stevie", last_name: "Johnson", position: "WR",player_id: 2950)
    FootballPlayer.create(first_name: "Antonio", last_name: "Brown", position: "WR",player_id: 11056)
    FootballPlayer.create(first_name: "Greg", last_name: "Jennings", position: "WR",player_id: 6597)
    FootballPlayer.create(first_name: "Julio", last_name: "Jones", position: "WR",player_id: 13291)
    FootballPlayer.create(first_name: "Dez", last_name: "Bryant", position: "WR",player_id: 11270)
    FootballPlayer.create(first_name: "Reggie", last_name: "Wayne", position: "WR",player_id: 5002)
    FootballPlayer.create(first_name: "Brandon", last_name: "Lloyd", position: "WR",player_id: 8694)
    FootballPlayer.create(first_name: "Pierre", last_name: "Garcon", position: "WR",player_id: 6767)
    FootballPlayer.create(first_name: "Laurent", last_name: "Robinson", position: "WR",player_id: 12081)
    FootballPlayer.create(first_name: "DeSean", last_name: "Jackson", position: "WR",player_id: 3943)
    FootballPlayer.create(first_name: "Jabar", last_name: "Gaffney", position: "WR",player_id: 8685)
    FootballPlayer.create(first_name: "Darrius", last_name: "Heyward-Bey", position: "WR",player_id: 8771)
    FootballPlayer.create(first_name: "Michael", last_name: "Crabtree", position: "WR",player_id: 9331)
    FootballPlayer.create(first_name: "Torrey", last_name: "Smith", position: "WR",player_id: 12830)
    FootballPlayer.create(first_name: "Nate", last_name: "Burleson", position: "WR",player_id: 11982)
    FootballPlayer.create(first_name: "Jeremy", last_name: "Maclin", position: "WR",player_id: 8914)
    FootballPlayer.create(first_name: "Anquan", last_name: "Boldin", position: "WR",player_id: 11712)
    FootballPlayer.create(first_name: "Malcom", last_name: "Floyd(SD)", position: "WR",player_id: 7711)
    FootballPlayer.create(first_name: "Steve", last_name: "Breaston", position: "WR",player_id: 3022)
    FootballPlayer.create(first_name: "Doug", last_name: "Baldwin", position: "WR",player_id: 13460)
    FootballPlayer.create(first_name: "Santonio", last_name: "Holmes", position: "WR",player_id: 11697)
    FootballPlayer.create(first_name: "Mike", last_name: "Williams(TB)", position: "WR",player_id: 12412)
    FootballPlayer.create(first_name: "Lance", last_name: "Moore", position: "WR",player_id: 6768)
    FootballPlayer.create(first_name: "David", last_name: "Nelson", position: "WR",player_id: 10946)
    FootballPlayer.create(first_name: "Early", last_name: "Doucet", position: "WR",player_id: 6048)
    FootballPlayer.create(first_name: "Deion", last_name: "Branch", position: "WR",player_id: 12374)
    FootballPlayer.create(first_name: "Greg", last_name: "Little", position: "WR",player_id: 12874)
    FootballPlayer.create(first_name: "Denarius", last_name: "Moore", position: "WR",player_id: 13069)
    FootballPlayer.create(first_name: "Plaxico", last_name: "Burress", position: "WR",player_id: 6160)
    FootballPlayer.create(first_name: "Dexter", last_name: "McCluster", position: "WR",player_id: 11220)
    FootballPlayer.create(first_name: "Titus", last_name: "Young", position: "WR",player_id: 13224)
    FootballPlayer.create(first_name: "James", last_name: "Jones", position: "WR",player_id: 6302)
    FootballPlayer.create(first_name: "Eric", last_name: "Decker", position: "WR",player_id: 11182)
    FootballPlayer.create(first_name: "Robert", last_name: "Meachem", position: "WR",player_id: 5741)
    FootballPlayer.create(first_name: "Miles", last_name: "Austin", position: "WR",player_id: 3330)
    FootballPlayer.create(first_name: "Andre", last_name: "Roberts", position: "WR",player_id: 11565)
    FootballPlayer.create(first_name: "Santana", last_name: "Moss", position: "WR",player_id: 1944)
    FootballPlayer.create(first_name: "Jason", last_name: "Avant", position: "WR",player_id: 1986)
    FootballPlayer.create(first_name: "Brandon", last_name: "LaFell", position: "WR",player_id: 11463)
    FootballPlayer.create(first_name: "Joshua", last_name: "Cribbs", position: "WR",player_id: 4291)
    FootballPlayer.create(first_name: "Mario", last_name: "Manningham", position: "WR",player_id: 1904)
    FootballPlayer.create(first_name: "Demaryius", last_name: "Thomas", position: "WR",player_id: 11197)
    FootballPlayer.create(first_name: "Austin", last_name: "Collie", position: "WR",player_id: 8606)
    FootballPlayer.create(first_name: "Davone", last_name: "Bess", position: "WR",player_id: 254)
    FootballPlayer.create(first_name: "Brian", last_name: "Hartline", position: "WR",player_id: 8330)
    FootballPlayer.create(first_name: "Sidney", last_name: "Rice", position: "WR",player_id: 459)
    FootballPlayer.create(first_name: "Kevin", last_name: "Walter", position: "WR",player_id: 2065)
    FootballPlayer.create(first_name: "Legedu", last_name: "Naanee", position: "WR",player_id: 1967)
    FootballPlayer.create(first_name: "Jacoby" ,last_name: "Jones", position: "WR",player_id: 5100)
    FootballPlayer.create(first_name: "Devery", last_name: "Henderson", position: "WR",player_id: 6717)
    FootballPlayer.create(first_name: "Harry", last_name: "Douglas", position: "WR",player_id: 6211)
    FootballPlayer.create(first_name: "Andre", last_name: "Johnson", position: "WR",player_id: 2429)
    FootballPlayer.create(first_name: "Brandon", last_name: "Gibson", position: "WR",player_id: 10034)
    FootballPlayer.create(first_name: "Golden", last_name: "Tate", position: "WR",player_id: 11611)
    FootballPlayer.create(first_name: "Arrelious", last_name: "Benn", position: "WR",player_id: 11501)
    FootballPlayer.create(first_name: "Mohamed", last_name: "Massaquoi", position: "WR",player_id: 8487)
    FootballPlayer.create(first_name: "Andre", last_name: "Caldwell", position: "WR",player_id: 3989)
    FootballPlayer.create(first_name: "Jeremy", last_name: "Kerley", position: "WR",player_id: 12794)
    FootballPlayer.create(first_name: "Devin", last_name: "Hester", position: "WR",player_id: 7082)
    FootballPlayer.create(first_name: "Earl", last_name: "Bennett", position: "WR",player_id: 8967)
    FootballPlayer.create(first_name: "Vincent", last_name: "Brown", position: "WR",player_id: 13078)
    FootballPlayer.create(first_name: "Emmanuel", last_name: "Sanders", position: "WR",player_id: 11063)
    FootballPlayer.create(first_name: "Chaz", last_name: "Schilens", position: "WR",player_id: 6412)
    FootballPlayer.create(first_name: "Kenny", last_name: "Britt", position: "WR",player_id: 8532)
    FootballPlayer.create(first_name: "Jacoby", last_name: "Ford(RAI)", position: "WR",player_id: 11230)
    FootballPlayer.create(first_name: "Derek", last_name: "Hagan", position: "WR",player_id: 12513)
    FootballPlayer.create(first_name: "Jonathan", last_name: "Baldwin", position: "WR",player_id: 13031)
    FootballPlayer.create(first_name: "Chad", last_name: "Ochocinco", position: "WR",player_id: 8447)
    FootballPlayer.create(first_name: "Donald", last_name: "Jones", position: "WR",player_id: 10944)
    FootballPlayer.create(first_name: "Mike", last_name: "Williams(Sea)", position: "WR",player_id: 12272)
    FootballPlayer.create(first_name: "Eddie", last_name: "Royal", position: "WR",player_id: 7389)
    FootballPlayer.create(first_name: "Josh", last_name: "Morgan", position: "WR",player_id: 5537)
    FootballPlayer.create(first_name: "Leonard", last_name: "Hankerson", position: "WR",player_id: 13162)
    FootballPlayer.create(first_name: "Kevin", last_name: "Ogletree", position: "WR",player_id: 8846)
    FootballPlayer.create(first_name: "Donnie", last_name: "Avery", position: "WR",player_id: 2730)
    FootballPlayer.create(first_name: "Danny", last_name: "Amendola", position: "WR",player_id: 9906)
    FootballPlayer.create(first_name: "Jordan", last_name: "Shipley", position: "WR",player_id: 11034)
    FootballPlayer.create(first_name: "Brandon", last_name: "Stokley", position: "WR",player_id: 12343)
    FootballPlayer.create(first_name: "Alshon", last_name: "Jeffery", position: "WR",player_id: 14187)
    FootballPlayer.create(first_name: "Brandon", last_name: "Tate", position: "WR",player_id: 8373)
    FootballPlayer.create(first_name: "Mohamed", last_name: "Sanu", position: "WR",player_id: 13878)
    FootballPlayer.create(first_name: "Ryan", last_name: "Broyles", position: "WR",player_id: 14203)
    FootballPlayer.create(first_name: "Kendall", last_name: "Wright", position: "WR",player_id: 13957)
    FootballPlayer.create(first_name: "T.Y.", last_name: "Hilton", position: "WR",player_id: 14005)
    FootballPlayer.create(first_name: "Brian", last_name: "Quick", position: "WR",player_id: 14424)
    FootballPlayer.create(first_name: "Jarius", last_name: "Wright", position: "WR",player_id: 14465)
    FootballPlayer.create(first_name: "Greg", last_name: "Childs", position: "WR",player_id: 14441)
    FootballPlayer.create(first_name: "Jerrel", last_name: "Jernigan", position: "WR",player_id: 13142)
    FootballPlayer.create(first_name: "Rueben", last_name: "Randle", position: "WR",player_id: 14242)
    FootballPlayer.create(first_name: "Stephen", last_name: "Hill", position: "WR",player_id: 13817)
    FootballPlayer.create(first_name: "Randy", last_name: "Moss", position: "WR",player_id: 4154)
    FootballPlayer.create(first_name: "A.J.", last_name: "Jenkins", position: "WR",player_id: 14502)
    FootballPlayer.create(first_name: "David", last_name: "Gettis", position: "WR",player_id: 11452)
    FootballPlayer.create(first_name: "Justin", last_name: "Blackmon", position: "WR",player_id: 14019)
    FootballPlayer.create(first_name: "Armon", last_name: "Binns", position: "WR",player_id: 12978)
    FootballPlayer.create(first_name: "Lestar", last_name: "Jean", position: "WR",player_id: 12942)
    FootballPlayer.create(first_name: "Chris", last_name: "Ivory", position: "RB", player_id: 12239)
  end
end